repos:
  - repo: local
    hooks:
      - id: ormolu
        name: ormolu
        entry: ormolu -i
        language: system
        files: '\.hs$'
      - id: hlint
        name: hlint
        entry: hlint
        language: system
        files: '\.hs$'
