name: lint
on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
      - name: Install dependencies
        run: |
          cabal install ormolu
          pip install pre-commit
      - run: pre-commit run --all-files --show-diff-on-failure


