name: release
on: workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs:
      - build

    env:
      VERSION: ${{ needs.build.outputs.version }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: cherf-binary-linux-x86_64
          path: ./bin/
      - uses: actions/download-artifact@v4
        with:
          name: cherf-binary-osx-x86_64
          path: ./bin/
      - uses: actions/download-artifact@v4
        with:
          name: cherf-binary-osx-arm64
          path: ./bin/
      - uses: actions/download-artifact@v4
        with:
          name: cherf-binary-windows-x86_64
          path: ./bin/
      - run: git log --oneline --decorate > /tmp/changelog
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          body_path: /tmp/changelog
          draft: true
          target_commitish: ${{ github.sha }}
          files: |
            bin/cherf-${{ env.VERSION }}-linux-x86_64
            bin/cherf-${{ env.VERSION }}-osx-x86_64
            bin/cherf-${{ env.VERSION }}-osx-arm64
            bin/cherf-${{ env.VERSION }}-windows-x86_64.exe
          fail_on_unmatched_files: true
